openapi: 3.0.3

info:
  title: Short URL API
  version: 1.0.0

paths:
  /short-urls:
    post:
      tags:
        - ShortUrls
      operationId: createShortUrl
      summary: Create a short URL

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateShortUrlRequest'

      responses:
        '201':
          description: Short URL created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateShortUrlResponse'

  /{code}:
    get:
      tags:
        - ShortUrls
      operationId: redirectShortUrl
      summary: Redirect to the original URL

      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string

      responses:
        '302':
          description: Redirect to original URL
          headers:
            Location:
              description: Original URL
              schema:
                type: string
                format: uri

        '404':
          description: Short URL not found

components:
  schemas:
    CreateShortUrlRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri

    CreateShortUrlResponse:
      type: object
      required:
        - shortUrl
      properties:
        shortUrl:
          type: string
          format: uri